/**
 * The stock set: the fifteen animals the game shipped with.
 *
 * Character ids are permanent once deployed — see the note in ./index.ts.
 */

import { tone, type CharacterSet } from '~/utils/characters'

export default {
	id: 'animals',
	name: 'どうぶつ',
	tagline: 'くまからライオンまで、なじみのある 15 匹',
	characters: [
		{
			id: 'bear',
			name: 'くまごろう',
			emoji: '🐻',
			tagline: 'のっそり低音',
			image: '/characters/animals/bear.svg',
			voice: {
				pitchRatio: 0.72,
				vibratoRate: 0,
				vibratoDepth: 0,
				ringModHz: 0,
				ringModDepth: 0,
				tone: tone(5, 900, -3, 1, -4),
			},
		},
		{
			id: 'rabbit',
			name: 'うさぴょん',
			emoji: '🐰',
			tagline: 'ぴょこぴょこ高音',
			image: '/characters/animals/rabbit.svg',
			voice: {
				pitchRatio: 1.42,
				vibratoRate: 0,
				vibratoDepth: 0,
				ringModHz: 0,
				ringModDepth: 0,
				tone: tone(-4, 2600, 3, 1, 2),
			},
		},
		{
			id: 'fox',
			name: 'こんきち',
			emoji: '🦊',
			tagline: 'すこし高めの早口',
			image: '/characters/animals/fox.svg',
			voice: {
				pitchRatio: 1.16,
				vibratoRate: 0,
				vibratoDepth: 0,
				ringModHz: 0,
				ringModDepth: 0,
				tone: tone(-2, 3000, 4, 1.2, 1),
			},
		},
		{
			id: 'tanuki',
			name: 'ぽんぽこ',
			emoji: '🦝',
			tagline: 'まるっと落ち着いた声',
			image: '/characters/animals/tanuki.svg',
			voice: {
				pitchRatio: 0.86,
				vibratoRate: 0,
				vibratoDepth: 0,
				ringModHz: 0,
				ringModDepth: 0,
				tone: tone(3, 1200, 2, 0.9, -2),
			},
		},
		{
			id: 'cat',
			name: 'にゃんきち',
			emoji: '🐱',
			tagline: 'つんとした高音',
			image: '/characters/animals/cat.svg',
			voice: {
				pitchRatio: 1.32,
				vibratoRate: 0,
				vibratoDepth: 0,
				ringModHz: 0,
				ringModDepth: 0,
				tone: tone(-3, 3400, 3, 1.4, 2),
			},
		},
		{
			id: 'dog',
			name: 'わんすけ',
			emoji: '🐶',
			tagline: 'ちょっとだけ低い',
			image: '/characters/animals/dog.svg',
			voice: {
				pitchRatio: 0.92,
				vibratoRate: 0,
				vibratoDepth: 0,
				ringModHz: 0,
				ringModDepth: 0,
				tone: tone(2, 800, 3, 0.8, -1),
			},
		},
		{
			id: 'owl',
			name: 'ふくろうはかせ',
			emoji: '🦉',
			tagline: 'こもった重低音',
			image: '/characters/animals/owl.svg',
			voice: {
				pitchRatio: 0.78,
				vibratoRate: 0,
				vibratoDepth: 0,
				ringModHz: 0,
				ringModDepth: 0,
				tone: tone(4, 500, 5, 0.7, -8),
			},
		},
		{
			id: 'penguin',
			name: 'ぺんぺん',
			emoji: '🐧',
			tagline: 'ぱたぱた明るい声',
			image: '/characters/animals/penguin.svg',
			voice: {
				pitchRatio: 1.24,
				vibratoRate: 0,
				vibratoDepth: 0,
				ringModHz: 0,
				ringModDepth: 0,
				tone: tone(-2, 2200, 3, 1, 1),
			},
		},
		{
			id: 'frog',
			name: 'けろすけ',
			emoji: '🐸',
			tagline: 'げこげこ潰れ声',
			image: '/characters/animals/frog.svg',
			voice: {
				pitchRatio: 0.66,
				vibratoRate: 0,
				vibratoDepth: 0,
				ringModHz: 55,
				ringModDepth: 0.22,
				tone: tone(2, 700, 6, 1.6, -6),
			},
		},
		{
			id: 'sheep',
			name: 'めーちゃん',
			emoji: '🐑',
			tagline: 'ふるえる甘い声',
			image: '/characters/animals/sheep.svg',
			voice: {
				pitchRatio: 1.1,
				vibratoRate: 5.5,
				vibratoDepth: 0.55,
				ringModHz: 0,
				ringModDepth: 0,
				tone: tone(-1, 2000, 2, 1, 1),
			},
		},
		{
			id: 'dragon',
			name: 'どらごん',
			emoji: '🐲',
			tagline: '地の底からの声',
			image: '/characters/animals/dragon.svg',
			voice: {
				pitchRatio: 0.58,
				vibratoRate: 0,
				vibratoDepth: 0,
				ringModHz: 0,
				ringModDepth: 0,
				tone: tone(7, 600, 3, 0.8, -6),
			},
		},
		{
			id: 'robot',
			name: 'ロボ丸',
			emoji: '🤖',
			tagline: 'ビリビリ電子音',
			image: '/characters/animals/robot.svg',
			// the disguise here comes from the ring modulator, not the pitch
			voice: {
				// deliberately not exactly 1.0: a static grain phase would turn the
				// shifter's two taps into a fixed comb filter
				pitchRatio: 0.94,
				vibratoRate: 0,
				vibratoDepth: 0,
				ringModHz: 42,
				ringModDepth: 0.85,
				tone: tone(-6, 1600, 6, 2, 3),
			},
		},
		{
			id: 'alien',
			name: 'うちゅうくん',
			emoji: '👽',
			tagline: 'きんきん宇宙声',
			image: '/characters/animals/alien.svg',
			voice: {
				pitchRatio: 1.62,
				vibratoRate: 7,
				vibratoDepth: 0.2,
				ringModHz: 0,
				ringModDepth: 0,
				tone: tone(-8, 3800, 5, 1.5, 3),
			},
		},
		{
			id: 'ghost',
			name: 'おばけん',
			emoji: '👻',
			tagline: 'ゆらゆら不気味な声',
			image: '/characters/animals/ghost.svg',
			voice: {
				pitchRatio: 0.82,
				vibratoRate: 3.2,
				vibratoDepth: 0.85,
				ringModHz: 0,
				ringModDepth: 0,
				tone: tone(2, 1100, -4, 0.8, -3),
			},
		},
		{
			id: 'lion',
			name: 'らいおん丸',
			emoji: '🦁',
			tagline: 'どっしり太い声',
			image: '/characters/animals/lion.svg',
			voice: {
				pitchRatio: 0.7,
				vibratoRate: 0,
				vibratoDepth: 0,
				ringModHz: 0,
				ringModDepth: 0,
				tone: tone(6, 700, 4, 0.9, -5),
			},
		},
	],
} satisfies CharacterSet
